# Generated by Django 4.1 on 2022-11-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="slug",
            field=models.SlugField(default="pet", max_length=100, unique=True),
        ),
    ]
