# Generated by Django 4.1 on 2022-11-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_pet_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="", max_length=100, unique=True
            ),
        ),
    ]
